### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by egawiser**
Really just testing if I have write access, but hopefully it's a net improvement.

### CODE REVIEW

**Comment by egawiser** [comment]
Aha - it created a fork when I tried to edit README.md because I do *not* have write permission in the main repo.  That's probably not the desired approach.

**Comment by rmandelb** [comment]
Currently this repo has 5 people with admin access and nobody with write access, just FYI.  The admins are @annmapo @heatherprince @jablazek @nikosarcevic @tilmantroester .  (I'm an LSSTDESC organization admin so I also have admin access.)  Perhaps the admins could establish a team with write access and add people to it, or I'm happy to help with that...

**Comment by jablazek** [comment]
I've started a new team and added @heatherprince and @egawiser to it. The team should have write permission.

**Comment by nikosarcevic** [comment]
> I've started a new team and added @heatherprince and @egawiser to it. The team should have write permission.

shall we then use this repo for everything in the future? I think @heatherprince  said she has some code on her personal repo.

I have just played around with my pipeline and im happy to report I can obtain a VERY good SRD-like data vector -- so if that is needed maybe we can open an issue?

**Comment by heatherprince** [comment]
Thank you Rachel and Jonathan for sorting that out! Niko, I think we should
use this repo in the future and keep track of things with issues. I will
move any relevant code I have over. We can discuss further at this week's
co-working session!

Thanks,
Heather

**Comment by egawiser** [comment]
Closing now that I have write permission and was able to udpate the readme directly.

**Pull request closed without merging**
